### ISSUE TITLE
Assertion Error on version > 0.2.1 with pytest option '-p no:cacheprovider'

### ISSUE THREAD

**Issue by techman83** [businho/pytest-ruff#27]
Since pytest-ruff 0.2.1, I've noticed an issue with an assertion error relating to the `get_stash` method within the pytest compatibility layer.

https://github.com/businho/pytest-ruff/blob/main/pytest_ruff/_pytest_compat.py#L41

```
/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/pytest_ruff/_pytest_compat.py:41: AssertionError
=========================== short test summary info ============================
ERROR src/hello/__init__.py::ruff - assert <object object at 0x7fd14fd28df0> is not <object object at 0x7fd14fd28df0>
ERROR src/hello/ruff.py::ruff - assert <object object at 0x7fd14fd2be10> is not <object object at 0x7fd14fd2be10>
============================== 2 errors in 0.20s ===============================
```

I've created a cut down project to demonstrate the issue, based around this pyproject.toml
```toml
[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "hello"
version = "0.0.1"
dependencies = ["pytest", "pytest-ruff"]

[project.scripts]
ruff-hello = "hello.ruff:world"

[tool.pytest.ini_options]
pythonpath = "src"
addopts = "-p no:cacheprovider --ruff"

[tool.ruff]
preview = true

[tool.ruff.lint]
select = [
    # flake8
    "A", "ARG", "B", "BLE", "C4", "PIE", "RET", "SIM", "S",
    "F",  # pyflakes
    "N",  # pep8-nameing
    "PL", # pylint
    "E",  # error
    "W",  # warning
    "PTH", # pathlib
    "RUF", # ruff
]
```

Examples
- 0.2.1 - working -> https://github.com/techman83/test-pytest-ruff/actions/runs/9870232427/job/27255534792
- 0.3 assertion error -> https://github.com/techman83/test-pytest-ruff/actions/runs/9870232427/job/27255535102
- 0.3.1 assertion error -> https://github.com/techman83/test-pytest-ruff/actions/runs/9870232427/job/27255535354
- 0.3.2 assertion error -> https://github.com/techman83/test-pytest-ruff/actions/runs/9870232427/job/27255535647
- 0.4.0 assertion error -> https://github.com/techman83/test-pytest-ruff/actions/runs/9870232427/job/27255535898

It appears to be related to config file discovery, as commenting out `assert stash is not missing` the tests do run, but use the default ruff config.
